name: wzlib
description: A MapleStory WZ files repacking library written in Dart language.
version: 0.0.1
homepage: https://github.com/genment/wzlib-dart

environment:
  sdk: '>=2.17.1 <3.0.0'


dependencies:
  path: ^1.8.0
  characters: ^1.2.0
  encrypt: ^5.0.1
  archive: ^3.2.2

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
