name: wzlib
description: A starting point for Dart libraries or applications.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  path: ^1.8.0
  characters: ^1.2.0
  encrypt: ^5.0.1
  archive: ^3.2.2

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
